-- Create tables for digital invitation system

-- Users table (extends Supabase auth.users)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) PRIMARY KEY,
  name text,
  phone text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Invitations table
CREATE TABLE public.invitations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('wedding', 'engagement', 'aqiqah', 'birthday', 'corporate')),
  owner_id uuid REFERENCES public.profiles(id) NOT NULL,
  title text NOT NULL,
  groom jsonb,
  bride jsonb,
  date jsonb,
  location jsonb,
  story text,
  gallery text[] DEFAULT '{}',
  theme_config jsonb NOT NULL DEFAULT '{}',
  guest_count integer NOT NULL DEFAULT 100 CHECK (guest_count >= 10 AND guest_count <= 2000),
  active_days integer NOT NULL DEFAULT 30 CHECK (active_days >= 7 AND active_days <= 365),
  total_price integer NOT NULL DEFAULT 75000,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'paid', 'expired')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Guests table
CREATE TABLE public.guests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invitation_id bigint REFERENCES public.invitations(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  group_name text DEFAULT 'Friends',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'opened', 'rsvp-yes', 'rsvp-no')),
  unique_link text UNIQUE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Guest book table
CREATE TABLE public.guest_book (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invitation_id bigint REFERENCES public.invitations(id) ON DELETE CASCADE NOT NULL,
  guest_name text NOT NULL,
  message text NOT NULL,
  photo text,
  reaction text,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Payments table
CREATE TABLE public.payments (
  id text PRIMARY KEY,
  invitation_id bigint REFERENCES public.invitations(id) ON DELETE CASCADE NOT NULL,
  order_id text UNIQUE NOT NULL,
  amount integer NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed', 'expired')),
  payment_type text,
  transaction_id text,
  payment_details jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes
CREATE INDEX idx_invitations_owner_id ON public.invitations(owner_id);
CREATE INDEX idx_invitations_slug ON public.invitations(slug);
CREATE INDEX idx_invitations_status ON public.invitations(status);
CREATE INDEX idx_guests_invitation_id ON public.guests(invitation_id);
CREATE INDEX idx_guests_status ON public.guests(status);
CREATE INDEX idx_guest_book_invitation_id ON public.guest_book(invitation_id);
CREATE INDEX idx_guest_book_is_visible ON public.guest_book(is_visible);
CREATE INDEX idx_payments_invitation_id ON public.payments(invitation_id);
CREATE INDEX idx_payments_status ON public.payments(status);

-- Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_book ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Profiles: Users can only access their own profile
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Invitations: Users can only access their own invitations
CREATE POLICY "Users can view own invitations" ON public.invitations
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "Users can create own invitations" ON public.invitations
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Users can update own invitations" ON public.invitations
  FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY "Users can delete own invitations" ON public.invitations
  FOR DELETE USING (auth.uid() = owner_id);

-- Invitations: Public invitations are readable by everyone
CREATE POLICY "Published invitations are viewable by everyone" ON public.invitations
  FOR SELECT USING (status = 'published' OR status = 'paid');

-- Guests: Users can only access guests of their own invitations
CREATE POLICY "Users can view own guests" ON public.guests
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = guests.invitation_id
      AND invitations.owner_id = auth.uid()
    )
  );

CREATE POLICY "Users can manage own guests" ON public.guests
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = guests.invitation_id
      AND invitations.owner_id = auth.uid()
    )
  );

-- Guest book: Public entries are readable by everyone for published invitations
CREATE POLICY "Guest book is viewable for published invitations" ON public.guest_book
  FOR SELECT USING (
    is_visible = true AND
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = guest_book.invitation_id
      AND (invitations.status = 'published' OR invitations.status = 'paid')
    )
  );

CREATE POLICY "Users can manage own guest book" ON public.guest_book
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = guest_book.invitation_id
      AND invitations.owner_id = auth.uid()
    )
  );

-- Payments: Users can only access their own payments
CREATE POLICY "Users can view own payments" ON public.payments
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = payments.invitation_id
      AND invitations.owner_id = auth.uid()
    )
  );

CREATE POLICY "Users can manage own payments" ON public.payments
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.invitations
      WHERE invitations.id = payments.invitation_id
      AND invitations.owner_id = auth.uid()
    )
  );

-- Functions and triggers for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_invitations_updated_at
  BEFORE UPDATE ON public.invitations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Function to generate unique guest links
CREATE OR REPLACE FUNCTION public.generate_unique_guest_link()
RETURNS TRIGGER AS $$
BEGIN
  NEW.unique_link := 'https://undangan.mu/inv/' || 
    (SELECT slug FROM public.invitations WHERE id = NEW.invitation_id) || 
    '?to=' || encode(gen_random_bytes(16), 'hex');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER generate_guest_unique_link
  BEFORE INSERT ON public.guests
  FOR EACH ROW EXECUTE FUNCTION public.generate_unique_guest_link();

-- Storage policies for file uploads
-- Note: Storage policies must be configured via Supabase Dashboard
-- They use Supabase-specific SQL extensions not available in direct PostgreSQL connections
-- 
-- To configure storage policies:
-- 1. Go to Supabase Dashboard > Storage > Create bucket "invitations"
-- 2. Set bucket to Public or Private as needed
-- 3. Configure policies via Dashboard UI:
--    - "Users can upload to their own invitation folders"
--    - "Users can view their own invitation files"
--    - "Public access to published invitation files"